import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync } from 'fs';
import { join, basename } from 'path';
import { fileURLToPath } from 'url';
import mjml2html from 'mjml';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const mjmlDir = join(__dirname, 'mjml');
const compiledDir = join(__dirname, 'compiled');

// Ensure compiled directory exists
if (!existsSync(compiledDir)) {
  mkdirSync(compiledDir, { recursive: true });
}

// Convert kebab-case to PascalCase
function toPascalCase(str: string): string {
  return str.replace(/(^|-)([a-z])/g, (_, _sep, letter) => letter.toUpperCase());
}

// Convert kebab-case to camelCase
function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

// Get all .mjml files
const mjmlFiles = readdirSync(mjmlDir).filter(f => f.endsWith('.mjml'));

if (mjmlFiles.length === 0) {
  console.log('No .mjml files found in', mjmlDir);
  process.exit(0);
}

const exports: string[] = [];

for (const file of mjmlFiles) {
  const name = basename(file, '.mjml');
  const funcName = `render${toPascalCase(name)}`;
  const interfaceName = `${toPascalCase(name)}Data`;

  console.log(`Compiling ${file}...`);

  const mjmlSource = readFileSync(join(mjmlDir, file), 'utf-8');

  const { html, errors } = mjml2html(mjmlSource, {
    minify: false,
    validationLevel: 'soft',
  });

  if (errors.length > 0) {
    console.warn(`  Warnings for ${file}:`);
    errors.forEach(e => console.warn(`    - ${e.message}`));
  }

  // Detect {{placeholders}}
  const placeholderRegex = /\{\{(\w+)\}\}/g;
  const placeholders = new Set<string>();
  let match;
  while ((match = placeholderRegex.exec(html)) !== null) {
    placeholders.add(match[1]);
  }

  // Also scan MJML source for placeholders
  let mjmlMatch;
  const mjmlPlaceholderRegex = /\{\{(\w+)\}\}/g;
  while ((mjmlMatch = mjmlPlaceholderRegex.exec(mjmlSource)) !== null) {
    placeholders.add(mjmlMatch[1]);
  }

  const sortedPlaceholders = Array.from(placeholders).sort();

  // Generate TypeScript file
  const interfaceFields = sortedPlaceholders
    .map(p => `  ${p}: string;`)
    .join('\n');

  const replaceChain = sortedPlaceholders
    .map(p => `    .replace(/\\{\\{${p}\\}\\}/g, data.${p})`)
    .join('\n');

  const tsContent = `// Auto-generated by compile.ts — DO NOT EDIT
// Source: mjml/${file}

export interface ${interfaceName} {
${interfaceFields}
}

const template = ${JSON.stringify(html)};

export function ${funcName}(data: ${interfaceName}): string {
  return template
${replaceChain};
}
`;

  writeFileSync(join(compiledDir, `${name}.ts`), tsContent);
  console.log(`  → compiled/${name}.ts (${sortedPlaceholders.length} placeholder${sortedPlaceholders.length !== 1 ? 's' : ''})`);

  exports.push(`export { ${funcName} } from './${name}';`);
  exports.push(`export type { ${interfaceName} } from './${name}';`);
}

// Generate barrel index.ts
const indexContent = `// Auto-generated by compile.ts — DO NOT EDIT\n\n${exports.join('\n')}\n`;
writeFileSync(join(compiledDir, 'index.ts'), indexContent);

console.log(`\nDone! ${mjmlFiles.length} template(s) compiled.`);
